version: '3'
services:
  ipfs:
    image: ipfs/go-ipfs:latest
    container_name: ipfs_node
    ports:
      - "4001:4001"   # libp2p 통신 포트
      - "5001:5001"   # API 포트
      - "8080:8080"   # 게이트웨이 포트
    networks:
      - ipfs_net
    volumes:
      - ./ipfs_data:/data/ipfs
    restart: always

  uploader:
    build: ./uploader
    container_name: pinata_uploader
    depends_on:
      - ipfs
    networks:
      - ipfs_net
    environment:
      - PINATA_JWT=${PINATA_JWT}
      - FILE_PATH=${FILE_PATH}
    volumes:
      - ./uploader:/app
      - ./uploader/test_file.png:/app/test_file.png
    command: python /app/upload_to_pinata.py

networks:
  ipfs_net: