services:
  ipfs:
    image: ipfs/go-ipfs:latest
    container_name: ipfs_node
    ports:
      - "4001:4001"   # libp2p 통신 포트
      - "5001:5001"   # API 포트
      - "9090:8080"   # 게이트웨이 포트
    networks:
      - ipfs_net
    volumes:
      - ./ipfs_data:/data/ipfs
    restart: always

  uploader:
    build: ./ipfs_uploader
    container_name: pinata_uploader
    depends_on:
      - ipfs
    networks:
      - ipfs_net
    environment:
      - PINATA_JWT=${PINATA_JWT}
      - FILE_PATH=/app/shared/${FILENAME}
    volumes:
      - ./ipfs_uploader:/app
      - /home/ubuntu/Desktop/shared:/app/shared
    command: >
      bash -c "python /app/upload_to_pinata.py && echo Done > /app/shared/status.txt"

  jupyter:
    image: ny-pytorch
    runtime: nvidia
    ports:
      - "8888:8888"
    volumes:
      - ./jupyter:/workspace
    command: >
      jupyter notebook
      --ip=0.0.0.0
      --allow-root      
    restart: unless-stopped
networks:
  ipfs_net:
